[project]
name = "bgunyel"
version = "0.1.0"
description = "Bertan Günyel Github"
readme = "README.md"
authors = [
    { name = "Bertan Günyel", email = "bertan.gunyel@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "rich>=14.2.0",
]
